Repository eastlakehs/community-service-tracker, pull requests merged in 2020-08, with the labels that each got.

#20 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: project-management

#17 Create LICENSE
  LICENSE
Labels: project-management

#15 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: project-management

#16 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: project-management

#21 Creating Basic Body Page
  website/src/App.tsx
  website/src/Images/wolflogo.png
  website/src/Pages/Body/body.tsx
  website/src/styles/tailwind.in.css
  website/src/styles/tailwind.out.css
  website/tailwind.config.js
Labels: enhancement

#29 Footer and Screen Height Fix 2
  website/src/App.tsx
  website/src/Pages/Body/body.tsx
  website/src/Pages/Footer/footer.tsx
  website/src/styles/tailwind.out.css
Labels: bug, enhancement

#32 Padding Breakpoint
  website/src/Pages/Body/body.tsx
Labels: bug, enhancement

#34 Ignore tailwind.out.css
  website/.gitignore
  website/package.json
  website/src/App.tsx
  website/src/Pages/Header/helmet.tsx
  website/src/index.tsx
  website/src/styles/tailwind.out.css
  website/yarn.lock
Labels: bug

#60 Merging all of our table code and stuff
  website/.vscode/settings.json
  website/__tests__/App.test.tsx
  website/package.json
  website/src/App.tsx
  website/src/AppRouter.tsx
  website/src/Components/Body/body.tsx
  website/src/Components/Edit/edit.tsx
  website/src/Components/Entry/entry.tsx
  website/src/Components/Header/pageHeader.tsx
  website/src/Components/Login/loginForm.tsx
  website/src/Components/Login/notLoggedIn.tsx
  website/src/Components/Profile/profile.tsx
  website/src/Components/Table/filter.tsx
  website/src/Components/Table/page.tsx
  website/src/Components/Table/pageController.tsx
  website/src/Components/Table/table.tsx
  website/src/Components/Table/table.types.ts
  website/src/Components/Table/tableController.tsx
  website/src/Components/Validation/validation.test.ts
  website/src/Components/Validation/validation.ts
  website/src/Components/Validation/validationMessage.ts
  website/src/Firebase/firestore/firestoreData.type.ts
  website/src/Firebase/firestore/submitEdit.ts
  website/src/Firebase/firestore/useUserData.ts
  website/src/Firebase/firestore/useUserProfile.ts
  website/src/Firebase/linkAuth/signInWithLink.ts
  website/src/Firebase/linkAuth/signOut.ts
  website/src/Firebase/linkAuth/useIsSignedIn.ts
  website/src/Pages/editController.tsx
  website/src/Pages/home.tsx
  website/src/Pages/loading.tsx
  website/src/Pages/login.tsx
  website/src/Pages/profileController.tsx
  website/src/Pages/table.tsx
  website/src/Redux/editScreenSlice.ts
  website/src/Redux/exampleSlice.ts
  website/src/Redux/profileScreenSlice.ts
  website/src/Redux/signedInSlice.ts
  website/src/Redux/store.ts
  website/src/Redux/userDataSlice.ts
  website/yarn.lock
Labels: enhancement

#56 Updating Footer Email
  website/src/Components/Footer/footer.tsx
Labels: enhancement

#64 Clean Up 2
  website/src/Firebase/linkAuth/useIsSignedIn.ts
Labels: bug
