Repository eastlakehs/community-service-tracker, pull requests merged in 2021-04, with the labels that each got.

#127 Making UI Intuitive to Use
  website/src/Components/Admin/admin.tsx
  website/src/Components/Header/pageHeader.tsx
  website/src/Constants/isAdmin.test.ts
  website/src/Constants/isAdmin.ts
  website/src/Firebase/linkAuth/useIsSignedIn.ts
  website/src/Redux/signedInSlice.ts
Labels: bug, confirmed, enhancement

#134 [ADMIN]: Clear user data when switching profiles in admin view
  website/src/Components/Admin/admin.tsx
  website/src/Redux/userDataSlice.ts
Labels: bug, ready-for-merge

#133 Removing VSCode Folder
  .gitignore
  website/.vscode/settings.json
Labels: bug, ready-for-merge

#135 Fix redirect url based on prod/staging
  website/src/Firebase/setup.ts
Labels: bug, ready-for-merge

#118 Admin View WIP
  Firebase/functions/src/index.ts
  ReportGeneration/src/main.ts
  ReportGeneration/tsconfig.json
  website/src/AppRouter.tsx
  website/src/Cache/cacheBuilder.ts
  website/src/Cache/profileCache.ts
  website/src/Components/Admin/admin.tsx
  website/src/Components/Admin/search.test.ts
  website/src/Components/Admin/search.ts
  website/src/Components/Header/pageHeader.tsx
  website/src/Components/Login/loginForm.tsx
  website/src/Components/Table/adminUsersTable.tsx
  website/src/Components/Table/table.tsx
  website/src/Components/Validation/validation.test.ts
  website/src/Constants/isAdmin.test.ts
  website/src/Constants/isAdmin.ts
  website/src/Firebase/firestore/firestoreData.type.ts
  website/src/Firebase/firestore/getListOfAllUsers.ts
  website/src/Firebase/firestore/submitEdit.ts
  website/src/Firebase/linkAuth/useIsSignedIn.ts
  website/src/Firebase/setup.ts
  website/src/Pages/Admin.tsx
  website/src/Redux/signedInSlice.ts
  website/src/Redux/userDataSlice.ts
  website/tsconfig.json
Labels: enhancement

#129 Make GitHub actions faster by caching dependencies
  .github/workflows/main.yml
  .github/workflows/tests.yml
  Firebase/Tests/yarn.lock
Labels: actions, enhancement, ready-for-merge

#137 Adding Export Button to Table
  website/src/Components/Table/exporter/handleExport.ts
  website/src/Components/Table/table.tsx
  website/src/Firebase/firestore/getReport.ts
Labels: enhancement, ready-for-merge

#140 Table export csv [REOPEN]
  website/package.json
  website/src/Components/Table/exporter/handleExport.ts
  website/src/Components/Table/table.tsx
  website/src/Firebase/firestore/getReport.ts
  website/yarn.lock
Labels: bug, ready-for-merge
