Repository eastlakehs/community-service-tracker, pull requests merged in 2021-05, with the labels that each got.

#144 Make the repo more accessible
  CONTRIBUTING.md
  README.md
  website/package.json
  website/src/Components/Footer/footer.tsx
Labels: documentation, enhancement, ready-for-merge

#158 Change contact phone to email or phone, closing #123
  website/src/Components/Edit/edit.tsx
Labels: enhancement

#160 Recasing Through VSCode
  .github/workflows/main.yml
  .github/workflows/tests.yml
  README.md
  actions/build.sh
  actions/screenshots/.gitignore
  actions/screenshots/requirements.txt
  actions/screenshots/screenshot.py
  docs/images/wolflogo.png
  firebase/.firebaserc
  firebase/.gitignore
  firebase/Tests/.gitignore
  firebase/Tests/babel.config.js
  firebase/Tests/firestore.test.ts
  firebase/Tests/jest.config.js
  firebase/Tests/package.json
  firebase/Tests/tsconfig.json
  firebase/Tests/yarn.lock
  firebase/firebase.json
  firebase/firestore.indexes.json
  firebase/firestore.rules
  firebase/functions/.gitignore
  firebase/functions/package-lock.json
  firebase/functions/package.json
  firebase/functions/src/index.ts
  firebase/functions/tsconfig.json
  firebase/functions/tslint.json
  firebase/package-lock.json
  firebase/storage.rules
  report-generation/.gitignore
  report-generation/package.json
  report-generation/readme.md
  report-generation/src/Firestore2Object.ts
  report-generation/src/Object2SummaryCSV.ts
  report-generation/src/data.ts
  report-generation/src/main.ts
  report-generation/src/setup.ts
  report-generation/tsconfig.json
  report-generation/yarn.lock
  website/src/Cache/cacheBuilder.ts
  website/src/Components/Edit/edit.tsx
Labels: enhancement, ready-for-merge

#163 add functions linting to CI
  .github/workflows/tests.yml
  firebase/functions/package.json
  firebase/package-lock.json
Labels: actions, enhancement, ready-for-merge

#167 No screenshots from fork
  .github/workflows/main.yml
Labels: actions

#166 add tighter restrictions for the graduation year, fix #161
  website/src/components/validation/validation.test.ts
  website/src/components/validation/validation.ts
Labels: bug, enhancement, ready-for-merge

#169 Add a "notes" section to the edit page
  website/src/components/edit/edit.tsx
  website/src/components/validation/validation.ts
  website/src/firebase/firestore/firestoreData.type.ts
  website/src/redux/editScreenSlice.ts
Labels: enhancement

#171 Fixes #165
  website/src/components/admin/admin.tsx
Labels: bug

#173 Create backup.yml
  .github/workflows/backup.yml
  actions/backup.ts
  package.json
Labels: actions, enhancement

#176 Add a workflow to automatically update the copyright year on the license file
  .github/workflows/license.yml
  actions/license/update.py
Labels: actions, documentation, enhancement, project-management

#178 Fixes #131 Redirects admin to admin
  website/src/components/login/loginForm.tsx
  website/src/components/table/tableController.tsx
  website/src/pages/home.tsx
Labels: bug

#181 Automate firebase deploy
  .github/workflows/production.yml
  firebase/functions/package-lock.json
  firebase/functions/package.json
  firebase/functions/yarn.lock
Labels: actions

#182 Changed submit/edit page layout #170
  .gitignore
  website/src/components/edit/edit.tsx
Labels: enhancement

#184 Update License Action
  .github/workflows/license.yml
Labels: actions, bug

#189 Adding EHS PTSA Account to Website
  firebase/firestore.rules
  website/src/constants/isAdmin.test.ts
  website/src/constants/isAdmin.ts
Labels: enhancement

#188 Removing Reports Page and Moving It To Admin
  website/src/AppRouter.tsx
  website/src/components/reports/reportPage.tsx
  website/src/components/table/adminUsersTable.tsx
Labels: enhancement

#196 update yarn.lock for prettier
  yarn.lock
Labels: dependencies, format

#198 Adds a PR template and re-formats the issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/generic.md
Labels: documentation, format, project-management
